### ISSUE TITLE
How load firmware in st-link /2 

### ISSUE THREAD

**Issue by peri55** [cocus/vc288-alt-fw#4]
good evening, could you tell me how we load  firmware in st-ling

**Comment by cocus** [comment]
Hi, please use the IAR IDE to program it. You could use the st-link v2 utility to flash it, but you'll need to compile the .hex file first, and in order to do so, you'll need the IAR IDE. It's free.
You could use the prgramming port to connect to an stlink v2 (STM8 interface). Find the SWIM, NRST, GND and Vcc from the STM8.

**Comment by peri55** [comment]
Thank you very much ... for your quick answer ... I downloaded IAR Embedded Workbench . But is not succeed... It shows me in Voltage is U.U.U. and ammeter the iss show L. is slow light.

**Comment by cocus** [comment]
Hello, the firmware is not yet ready to be a drop-in replacement. Please read the readme file. 
However, it should display some values. Remember to flash the device and not debug it, since the debug PIN is also used in the display.

**Comment by peri55** [comment]
Thank you very much...
